### ISSUE TITLE
After running the code, there is a error shows up, and I add a line "On Error Resume Next", then the error gone.

### ISSUE THREAD

**Issue by jun-jing** [Vitosh/VBA_personal#5]
Below is the error Infos, Sorry for the Chinese error message. 
![image](https://user-images.githubusercontent.com/18417195/120350170-51e97400-c331-11eb-9fa3-1ce6692da205.png)

Anyway, I added a line there, then the issue is gone, I am not sure whether it will affect other parts of the whole script. The code I add below is like this:
![image](https://user-images.githubusercontent.com/18417195/120350491-9a089680-c331-11eb-845d-7a5b39bbd113.png)

I am just a newbie of using VBE, and I really thank you for your code, it really helps. I can see you really do a lot of things with VBA on Github, that's so exciting.

Best regards
Jesse

**Comment by jun-jing** [comment]
I did some research on this error, I guess it's because when any Microsoft Excel object element has nothing in it, then it will show the error. 

![image](https://user-images.githubusercontent.com/18417195/120352490-662e7080-c333-11eb-9bdc-ac4870ada2d6.png)

**Comment by Vitosh** [comment]
Hello there :smiley: 

I will take a better look in the next few days (if I do not forget), but take these points so far:
- Thanks for writing :)
- Never ever use `On Error Resume Next` as a "cure" to fix some code, because it ignores errors and this is a **bad practice**. It is to be used only in cases like the one below, when you know what can go wrong and it should be followed by `On Error GoTo 0`, so the effect from the `Resume Next` is fixed.
```
Function IsWorkbookOpen(wbk As Workbook) As Boolean
    'Opened Workbook, open workbook
    Dim checkWbk As Workbook
    
    On Error Resume Next
    Set checkWbk = Workbooks(wbk.Name)
    On Error GoTo 0
    
    If checkWbk Is Nothing Then
        IsWorkbookOpen = False
    Else
        IsWorkbookOpen = True
    End If
    
End Function
```
- In order to have the code without errors, add this library `Microsoft Visual Basic For Applications Extensibility 5.3.` to the VBE project. See the article - https://www.vitoshacademy.com/vba-listing-all-procedures-in-all-modules/. This library is added from "Extras>References" and then with a checkbox:
Microsoft Visual Basic For Applications Extensibility 5.3


![Screenshot from 2021-06-01 19-45-35](https://user-images.githubusercontent.com/4303858/120360936-f9ef4500-c311-11eb-900f-a8f30fa8ae5b.png)

- That's all, let me know whether it worked :+1:

**Comment by jun-jing** [comment]
> Hello there 😃
> 
> I will take a better look in the next few days (if I do not forget), but take these points so far:
> 
> * Thanks for writing :)
> * Never ever use `On Error Resume Next` as a "cure" to fix some code, because it ignores errors and this is a **bad practice**. It is to be used only in cases like the one below, when you know what can go wrong and it should be followed by `On Error GoTo 0`, so the effect from the `Resume Next` is fixed.
> 
> ```
> Function IsWorkbookOpen(wbk As Workbook) As Boolean
>     'Opened Workbook, open workbook
>     Dim checkWbk As Workbook
>     
>     On Error Resume Next
>     Set checkWbk = Workbooks(wbk.Name)
>     On Error GoTo 0
>     
>     If checkWbk Is Nothing Then
>         IsWorkbookOpen = False
>     Else
>         IsWorkbookOpen = True
>     End If
>     
> End Function
> ```
> 
> * In order to have the code without errors, add this library `Microsoft Visual Basic For Applications Extensibility 5.3.` to the VBE project. See the article - https://www.vitoshacademy.com/vba-listing-all-procedures-in-all-modules/. This library is added from "Extras>References" and then with a checkbox:
>   Microsoft Visual Basic For Applications Extensibility 5.3
> 
> ![Screenshot from 2021-06-01 19-45-35](https://user-images.githubusercontent.com/4303858/120360936-f9ef4500-c311-11eb-900f-a8f30fa8ae5b.png)
> 
> * That's all, let me know whether it worked 👍

Thank you so much for the advice and reference link.
Really appreciate that, and you got me, I am totally a newbie of VBE, anyway advice received, I won't use the "On Error" line without specific reason later.
And about the reference link, I have already refer the "Microsoft Visual Basic For Applications Extensibility 5.3" to my project, so I just wanna say, this issue doesn't have to all my VBA code, just some of them happen.

Best regards

**Comment by Vitosh** [comment]
Just a small clarification - the line you should care about and try to avoid is `On Error Resume Next`, the general error handling with `On Error GoTo SomePlace` is quite ok.
